### ISSUE TITLE
When I edit or save a .py file, it clears the local database

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#116]
Anytime I save a .py file, the character attached to my account gets wiped. Is this a bug or is it unavoidable? It would be nice to test a character, edit a .py file, then continue testing without restarting. Also, the constant create character screen makes me not want to do any work on fleshing out the introduction yet.

**Comment by klondikemarlen** [comment]
I believe that since we have a new database this probably isn't and issue any longer.
