### ISSUE TITLE
Convert Database to python Class.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/flask-game#121]
This should help separate the database from the game code and allow easier editing of both.
Provide unit tests for the database. Hide SQL code as far away as possible ... :P

**Comment by klondikemarlen** [comment]
I have a question about the database .... why do you have a `user_id` variable? Doesn't the `username` variable provide all the same options? I mean I'm sure there is a reason but I don't know what it is?
Do you have a Database schematic? I think they are called ERD's ...? Entity Relationship Diagram. Can I make one?

**Comment by klondikemarlen** [comment]
I am currently reading http://jackzheng.net/teaching/archive/cis3730-2010-fall/files/1.5-erd.pdf and will see what I can come up with.

**Comment by jimmy-gnahz** [comment]
Yeah we should create one. Some of the variables are redundant or unused.  The SQLite version doesn't support deleting fields.  Ideally, the fields should be grouped in separate tables, not how I did it (all in one table).

**Comment by klondikemarlen** [comment]
Are fields the same as attributes (table columns)? I will see what I can make ... mainly because there is enough data that I tend to lose track of what goes where. I am kind of shaky on the correct way to link tables ... Or is the link virtual? Like something that only exists in the mind of the programmer?
I have started building a relationship diagram here https://www.draw.io/#LUntitled%20Diagram.xml.

**Comment by klondikemarlen** [comment]
I think the way you designed it makes sense? You have a User table which is linked to a Character table and the character table holds all of the data about the character. I mean you could add a extra Locations tables and link that to Character plus an Item table ... but that is like farther down the road.

**Comment by klondikemarlen** [comment]
Work in progress see: #138 .
