### ISSUE TITLE
You always start the game with 25/5 Endurance

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#128]
I can't find where this is happening. Of course your endurance should never be higher than your max endurance.

**Comment by jimmy-gnahz** [comment]
how do I replicate the bug.  I.e. which account should you sign into where it displays 25/5.

On the one I usually test, admin admin, it works fine.

**Comment by elthran** [comment]
My sanctity also seems to be locked at a certain value?!?! It's not just enduruance, its both of them!!!

**Comment by klondikemarlen** [comment]
Fixed in database_v3 ... I will keep trying to get closer to merging.
