### ISSUE TITLE
Quests - Suggestions

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/flask-game#137]
May I suggest using self.heroes instead of self.myhero?
Then using:
if hero in list of quests and quest is completed
then update hero data?

That way two heroes can have the same quest active? Or something.

**Comment by elthran** [comment]
I have no idea what this means because I cannot comprehend how the server stores andcalls multiple heroes. The problem right now is that quests/items/abilities are attached (bilaterally) to a hero and then modify the heroes stats by using self.myHero.some_function()

How does that work if there are multiple heroes?

**Comment by klondikemarlen** [comment]
I believe that this calls for a many to many relationship. i.e each hero can have multiple quests, each quest can be held my many heroes. The database implement aside ... you can just make each hero have a "quests" variable and each quest have a "heroes" variable.

The database implementations would be the "heroes" variable in the Quest object would be a list of hero ids or hero names.

**Comment by klondikemarlen** [comment]
Building on current idea:
Quest Object
-Name
-description
-completed:False/True
-next_quests:[list of secondary quests that branch directly off this one, normally only one or two?]
-all_quests_in_set:[list of all quests connected to this one] -> self-referential a.k.k "node"?

I think that you may want to use node architecture for Quests.
Basically make current_stage point to a quest object. While next_stage points to the next quest that needs to be completed.
When next_stage is None then the current_stage is the last stage.

**Comment by klondikemarlen** [comment]
Implementing with new spec. See  593d41c
