### ISSUE TITLE
Merge branch database_v3 back into branch main.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/flask-game#138]
Finish working on database_v3 branch and merge it back into branch main. This should allow new work to move forward. I hope it will not brake everything to much.

I need to finish it a bit more first.

**Comment by elthran** [comment]
I can't wait for this to be complete! I will be gone until February 12, so definitely no rush :D

**Comment by klondikemarlen** [comment]
Replaced this with a milestone?
