### ISSUE TITLE
Ability page currently only displays Basic "All Known Abilities" when all ability points are spent.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/flask-game#153]
I need to improve on the original page as Ability page needs a switch to check different types of All Known Abilities. Currently defaults to Basic. Should probably list all the different types of known abilities.

Or it displays the page that matches the 'spec' that the last points were spent on.
If last point was spend on 'Class" spec then will always display class abilities.

**Comment by elthran** [comment]
Abilities you have mastered don't show up, but abilities you have learned but not mastered show up.

**Comment by elthran** [comment]
Also, all unknown abilities show up twice on the ability page:
- Once under Unknown (THIS WILL CRASH DATABASE IF YOU CLICK)
- Once under Known/Mastered
