### ISSUE TITLE
If you create a new account, all accounts are broken.

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#155]
If you close app.py and relaunch it, then you can log back in.

**Comment by elthran** [comment]
It doesn't break it until you try to log in with the new account***

**Comment by klondikemarlen** [comment]
Bug is in app.py def home line 477 ish. Prebuilt objects should be pulled from the database rather
than added in new each time.

**Comment by klondikemarlen** [comment]
Fixed! f9f34393d7b7d35b7f53c25dceb85224a767768e. Plus added some coolness of pre-building a default account when I wipe the database.
