### ISSUE TITLE
Update of exp_percent

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#161]
You have a new attribute which is simply exp_percent (your current exp divided by your max exp).  Currently it is updated in the update_secondary_attributes(self) function in game.py

But it is buggy about when it updates. It realistically should update any time your current exp amount changes. At no other time does it need to update. This function is used so we can pass a % variable to HTML to tell it what to display, since you can't do any math inside HTML.

**Comment by klondikemarlen** [comment]
You need a validator. Let me look them up again and I will link it.

**Comment by klondikemarlen** [comment]
See https://github.com/elthran/flask-game/blob/master/flask-intro/quests.py
`@validates('active')
    def validate_active(self, key, flag):
        """Prevent quest being both active and completed at the same time.
        """
        assert self.completed != True
return flag`

You would need a validator for current_xp (and possibly when your max_xp changes).
`@validates('current_xp')
def validates_current_xp(self, key, value):
    self.xp_percent = max_xp / value 
    # or maybe self.xp_percent = max_xp / value * 100
    # and do the string conversion in HTML and add the % sign there.
`

This would go in the Hero class. It would require a class variable called xp_percent defined in the database/template thingy. You would never need to set the xp_percent explicitly. Only send the current_xp to the database and run and "update/commit" and then the the value of xp_percent would be the new percent. Which you could send back to the HTML and then format with the % sign.

**Comment by klondikemarlen** [comment]
I built the validator here a6598c9c79a15. I only changed like 20 lines of code but git says I rewrote the whole file from scratch :P.

**Comment by klondikemarlen** [comment]
You should be able to update the other percents to match.

**Comment by klondikemarlen** [comment]
The main (non-obvious) thing is order of operations. I had to assign a value to max_exp before assigning a value to current_exp in the __init__ for the Hero class.
