### ISSUE TITLE
If you buy a weapon and go to 'Profile' it will crash

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#168]
![test](https://cloud.githubusercontent.com/assets/11773722/24834914/c53f7a88-1d24-11e7-9303-c0d0d1a32dd9.jpg)

**Comment by klondikemarlen** [comment]
This is a problem with the load_template(self): function in items.py. It doesn't load all of the attributes for a multi-layered template. Only the first layer. 

I need to use recursion to load each layer until the Base layer is hit.

**Comment by klondikemarlen** [comment]
Fixed in 3948d9a. Now there is a new bug.

 
![image](https://cloud.githubusercontent.com/assets/23045206/25412481/cd0c29e0-29d7-11e7-9b97-0a58b1902d4a.png)

**Comment by klondikemarlen** [comment]
Fixed in 778c604.

And when did this happen?
![image](https://cloud.githubusercontent.com/assets/23045206/25412633/187e046a-29d9-11e7-9fb2-bb3598c7931c.png)
