### ISSUE TITLE
Set up static pages with css

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#18]
Instead of writing tons of html files with all of the layout in each one, we need to create a css file that lays out the template for our entire framework, and then the html files will need less text in them. But I have no idea how to do this.

**Comment by elthran** [comment]
It's something like
<!doctype html>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<div class=page>

At the start of each html page. But you need to edit the css file to the template.

**Comment by jimmy-gnahz** [comment]
Just add that one line:
"<link href="static/styles.css" rel="stylesheet" type="text/css" />"
under the bootstrap css link in each file.
