### ISSUE TITLE
Create a table of abilities

### ISSUE THREAD

**Issue by jimmy-gnahz** [elthran/flask-game#47]
Create the table of abilities names such as:
ID | Name  
1   | Learn  
2   | .....

Then upload the information here into the database.

**Comment by klondikemarlen** [comment]
Currently built Abilities table. See 0dd2ba7. I moved the all_abilities list into prebuilt_objects.py.
Will modify prebuilt_objects.py so that it loads everything directly into the database. All object that
use data from there must then query it directly from the database.

**Comment by klondikemarlen** [comment]
Implemented!  7986e50
