### ISSUE TITLE
Rewrite battle simulator

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#62]
It needs to incorporate all secondary attributes

**Comment by klondikemarlen** [comment]
I need some more data about what needs to be accomplished. Is the battle simulator a new module that needs to be created? Does it need an html display function for uses with the website? Or is it an offline tool for developers? Could you make a crude pencil sketch of what various functions should look like ?
:) I am pretty stoked to get to work but I am having trouble breaking the intro barrier.

**Comment by elthran** [comment]
Ok, I'll spend this week outlining some suggestions! We can collaborate on our ideas here and then I'll leave you to build it 💃
