### ISSUE TITLE
Upload the game files to a server, so users don't need flask

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#92]
Make it so that someone can login and play the game purely online. They shouldn't need Flask.

**Comment by klondikemarlen** [comment]
... do you have any idea of where to host the game? Like on what server platform site whatever? We would need a server/host that can run flask. Then we could push the latest stable changes to the server after testing on github. Then anyone could test the game ...

**Comment by elthran** [comment]
Yay!!!!!
