### ISSUE TITLE
Bug: Sometimes you win combat but you are at negative health.

### ISSUE THREAD

**Issue by elthran** [elthran/flask-game#93]
Easy fix.

**Comment by elthran** [comment]
I read through the code and I can't see how this can happen. :'( I'll see if the bug ever occurs again and screenshot it.

**Comment by jimmy-gnahz** [comment]
any update? @elthran

**Comment by elthran** [comment]
I've never been able to replicate it. But I'll keep my eye out! I don't think I'm crazy >.<
